// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'pattern_entity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_PatternEntity _$$_PatternEntityFromJson(Map<String, dynamic> json) =>
    _$_PatternEntity(
      item: $enumDecode(_$PatternsEnumMap, json['item']),
      header: json['header'] as String,
    );

Map<String, dynamic> _$$_PatternEntityToJson(_$_PatternEntity instance) =>
    <String, dynamic>{
      'item': _$PatternsEnumMap[instance.item],
      'header': instance.header,
    };

const _$PatternsEnumMap = {
  Patterns.LaunchScreen: 'LaunchScreen',
  Patterns.WelcomeAndGetStarted: 'WelcomeAndGetStarted',
  Patterns.Walkthrough: 'Walkthrough',
  Patterns.SignUp: 'SignUp',
  Patterns.Login: 'Login',
  Patterns.Verification: 'Verification',
  Patterns.AccountSetup: 'AccountSetup',
  Patterns.GuidedTourAndTutorial: 'GuidedTourAndTutorial',
  Patterns.Charts: 'Charts',
  Patterns.Progress: 'Progress',
  Patterns.DashboardAndStats: 'DashboardAndStats',
  Patterns.SizeGiude: 'SizeGiude',
  Patterns.BookmarksAndCollections: 'BookmarksAndCollections',
  Patterns.DownloadsAndAvailable: 'DownloadsAndAvailable',
  Patterns.Offline: 'Offline',
  Patterns.Playlists: 'Playlists',
  Patterns.Trash: 'Trash',
  Patterns.About: 'About',
  Patterns.ActionOption: 'ActionOption',
  Patterns.AcknowledgementAndSuccess: 'AcknowledgementAndSuccess',
  Patterns.Error: 'Error',
  Patterns.Confirmation: 'Confirmation',
  Patterns.Permission: 'Permission',
  Patterns.EmptyState: 'EmptyState',
  Patterns.Loading: 'Loading',
  Patterns.PullToRefresh: 'PullToRefresh',
  Patterns.CoachMarksAndInstruction: 'CoachMarksAndInstruction',
  Patterns.FeatureInfo: 'FeatureInfo',
  Patterns.SettingsAndPreference: 'SettingsAndPreference',
  Patterns.HelpAndSupport: 'HelpAndSupport',
  Patterns.Feedback: 'Feedback',
  Patterns.PrivacyPolicy: 'PrivacyPolicy',
  Patterns.TermsAndConditions: 'TermsAndConditions',
  Patterns.SuggestionAndSimilarItems: 'SuggestionAndSimilarItems',
  Patterns.Confetti: 'Confetti',
  Patterns.DarkMode: 'DarkMode',
  Patterns.Misc: 'Misc',
  Patterns.Shop: 'Shop',
  Patterns.SubscriptionAndPremium: 'SubscriptionAndPremium',
  Patterns.CartsAndBars: 'CartsAndBars',
  Patterns.CheckoutAndOrderReview: 'CheckoutAndOrderReview',
  Patterns.PaymentMethod: 'PaymentMethod',
  Patterns.OrderHistory: 'OrderHistory',
  Patterns.Pricing: 'Pricing',
  Patterns.WalletAndBallance: 'WalletAndBallance',
  Patterns.PromotionsAndRewards: 'PromotionsAndRewards',
  Patterns.Ads: 'Ads',
  Patterns.AchievementsAndAwards: 'AchievementsAndAwards',
  Patterns.ActivityAndNotification: 'ActivityAndNotification',
  Patterns.AddAndInviteFriends: 'AddAndInviteFriends',
  Patterns.Comments: 'Comments',
  Patterns.SocialFeed: 'SocialFeed',
  Patterns.FollowersAndFollowing: 'FollowersAndFollowing',
  Patterns.Leaderboard: 'Leaderboard',
  Patterns.ProfileAndAccount: 'ProfileAndAccount',
  Patterns.ReviewsAndRating: 'ReviewsAndRating',
  Patterns.GroupsAndCommunity: 'GroupsAndCommunity',
  Patterns.TimeLineAndHistory: 'TimeLineAndHistory',
  Patterns.Calendar: 'Calendar',
  Patterns.DateAndTime: 'DateAndTime',
  Patterns.TimeAndClocl: 'TimeAndClocl',
  Patterns.Reminder: 'Reminder',
  Patterns.LocationAndAddress: 'LocationAndAddress',
  Patterns.Map: 'Map',
  Patterns.Browser: 'Browser',
  Patterns.ChatBots: 'ChatBots',
  Patterns.AudioPlayer: 'AudioPlayer',
  Patterns.VideoPlayer: 'VideoPlayer',
  Patterns.AudioAndVideoRecorder: 'AudioAndVideoRecorder',
  Patterns.MediaEditor: 'MediaEditor',
  Patterns.CameraAndScanner: 'CameraAndScanner',
  Patterns.FiltersAndStickers: 'FiltersAndStickers',
  Patterns.Call: 'Call',
  Patterns.Home: 'Home',
  Patterns.DiscoverAndExplore: 'DiscoverAndExplore',
  Patterns.NewsFeed: 'NewsFeed',
  Patterns.ItemList: 'ItemList',
  Patterns.EmailsAndMessages: 'EmailsAndMessages',
  Patterns.Article: 'Article',
  Patterns.TVShowsAndMovie: 'TVShowsAndMovie',
  Patterns.PodcastAndSong: 'PodcastAndSong',
  Patterns.RecipeAndMenu: 'RecipeAndMenu',
  Patterns.Note: 'Note',
  Patterns.GoalAndTask: 'GoalAndTask',
  Patterns.Post: 'Post',
  Patterns.Stories: 'Stories',
  Patterns.Chat: 'Chat',
  Patterns.Game: 'Game',
  Patterns.Class: 'Class',
  Patterns.Event: 'Event',
  Patterns.Quiz: 'Quiz',
  Patterns.Product: 'Product',
  Patterns.AugementedReality: 'AugementedReality',
  Patterns.OtherContent: 'OtherContent',
  Patterns.AddAndCreate: 'AddAndCreate',
  Patterns.Edit: 'Edit',
  Patterns.Delete: 'Delete',
  Patterns.UploadAndDownload: 'UploadAndDownload',
  Patterns.Select: 'Select',
  Patterns.Move: 'Move',
  Patterns.Reorder: 'Reorder',
  Patterns.DrawAndAnnotate: 'DrawAndAnnotate',
  Patterns.Save: 'Save',
  Patterns.Cancel: 'Cancel',
  Patterns.SetSchedule: 'SetSchedule',
  Patterns.LikeAndUpvote: 'LikeAndUpvote',
  Patterns.FollowAndSubscribe: 'FollowAndSubscribe',
  Patterns.Share: 'Share',
  Patterns.FlagAndReport: 'FlagAndReport',
  Patterns.BanAndBlock: 'BanAndBlock',
  Patterns.FilterAndSort: 'FilterAndSort',
  Patterns.Search: 'Search',
  Patterns.TransferAndSendMoney: 'TransferAndSendMoney',
  Patterns.OtherAction: 'OtherAction',
};
